In [4]:
import numpy as np
import torch
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  1
Shape of t:  (7,)


In [6]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element t[0] t[1] t[-1] = 0.0 1.0 6.0
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # Slicing t[2:5] t[4:-1] = [2. 3. 4.] [4. 5.]
print('t[:2] t[3:]     = ', t[:2], t[3:]) # Slicing t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [9]:
# 2D array

t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim()) # Rank
print(t.size()) # Shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

# Slicing 은 끝번호에 해당하는 것은 포함 하지 않음!

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [12]:
# Broadcasring : 서로 크기가 다른 행렬들이 사칙 연산을 수행할 수 있도록 자동으로 크기를 맞춰서 연산을 수행
# Same Shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [13]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [14]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [18]:
# Multiplication & Matrix Multiplication
# : Element-wise 곱셈에선 서로 다른 크기의 행렬이 브로드캐스팅 된 후에 곱셈이 수행
# : 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것과 같은 결과를 얻게 됨.
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape) # 2 x 2
print('Shape of Matrix 2 : ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))



-------------
Mul vs Matmul
-------------
Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [19]:
# Mean
# : .mean()에서 dim을 인자로 주게 되면 어느 차원을 기준으로 평균을 구할지 설정가능
# : 아무 것도 설정하지 않으면 전체 평균을 계산
# : dim = 0은 첫번째 차원 즉 행을 기준으로 평균을 계산.
# : dim = 0이라는 것은 첫번째 차원을 의미. 행렬에서 첫번째 차원은 '행'을 의미
# : 그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미 -> '열'만 남기겠다는 의미
# : dim = 1은 두번째 차원 즉 열을 기준으로 평균을 계산
# : dim = -1은 마지막 차원으로 평균을 계산하는데 위의 예제에선 마지막 차원 = 열
# : t2.mean(dim=1)과 출력값이 동일

t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [20]:
# Can't Use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [21]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.mean())
print(t.mean(dim=0)) # ↓ : 행을 기준으로
print(t.mean(dim=1)) # → : 열을 기준으로
print(t.mean(dim=-1)) # 마지막 차원으로 평균을 계산

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [23]:
# Sum : 덧셈은 편균과 사용방법이 완전히 동일
t = torch.FloatTensor([[1, 2] , [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.sum())
print(t.sum(dim=0)) # ↓ : 행을 기준으로
print(t.sum(dim=1)) # → : 열을 기준으로
print(t.sum(dim=-1)) # 마지막 차원으로 평균을 계산

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [29]:
# Max & Argmax
# : Max는 최대값을 반환하고 Argmax는 최대값을 가진 인덱스를 반환
# : 차원을 지정하면 두개의 데이터를 뽑을 수 있음
# : t.max(dim=0)[0] 이 최대값 (max)를 나타내고,
# : t.max(dim=0)[1]이 최대값을 갖는 데이터 인덱스를 나타냄.
t = torch.FloatTensor([[1, 2] , [3, 4]])
# [ 1   3 ]   index 값
# [ 2   4 ]
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.max()) # Retunrs one Value : max
print(t.max(dim=0)) # Returns two Values : max and argmax
print('Max     : ', t.max(dim=0)[0])
print('Argmax  : ', t.max(dim=0)[1])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max     :  tensor([3., 4.])
Argmax  :  tensor([1, 1])


In [31]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [32]:
# View : 원소의 수를 유지하면서 텐서의 크기 변경.
t = np.array([[[0, 1, 2],
               [3, 4 ,5]],
              
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [33]:
print(ft.view([-1, 3]))  # -1 : pytorch가 알아서... 3 : 차원의 길이 3으로
print(ft.view([-1, 3]).shape) 
# 현재 3차원 텐서를 2차원 텐서로 변경하되 (?,3)의 크기로 변경하라는 의미.
# 내부적으로 크기 변환은 (2, 2, 3) -> (2 x 2, 3) -> (4, 3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [34]:
print(ft.view([-1, 1, 3])) # (? x 1 x 3)으로 변경
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
